package com.stickersync2;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

@Entity(tableName = "sticker_packs")
public class StickerPackEntity {
    @PrimaryKey
    private String id;
    private String name;
    private String sourceApp;
    private boolean isAutoGenerated;

    // Constructor
    public StickerPackEntity(String id, String name, String sourceApp, boolean isAutoGenerated) {
        this.id = id;
        this.name = name;
        this.sourceApp = sourceApp;
        this.isAutoGenerated = isAutoGenerated;
    }

    // Getters
    public String getId() { return id; }
    public String getName() { return name; }
    public String getSourceApp() { return sourceApp; }
    public boolean isAutoGenerated() { return isAutoGenerated; }

    // Setters
    public void setName(String name) { this.name = name; }
    public void setSourceApp(String sourceApp) { this.sourceApp = sourceApp; }
    public void setIsAutoGenerated(boolean isAutoGenerated) { this.isAutoGenerated = isAutoGenerated; }
}